# Generated by Django 4.2.13 on 2024-07-02 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('test_app', '0002_auto_20190520_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testgroup',
            name='restriction_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_restrictions', to='contenttypes.contenttype', verbose_name='restriction content type id'),
        ),
    ]
