# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-11-28 12:13
from __future__ import unicode_literals

from django.db import migrations
import protector.managers


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_auto_20190520_0958'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='testpost',
            managers=[
                ('objects', protector.managers.GenericGroupManager()),
            ],
        ),
    ]
