# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 08:38
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('protector', '0002_auto_20160607_0827'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='restriction',
            managers=[
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
