# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 12:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('protector', '0003_auto_20160607_0838'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name=b'description')),
                ('permission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.Permission')),
            ],
            options={
                'verbose_name': 'Permission Info',
                'verbose_name_plural': 'Permissions Info',
            },
        ),
        migrations.AlterModelManagers(
            name='restriction',
            managers=[
            ],
        ),
    ]
