# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-16 10:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protector', '0007_history_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='historygenericusertogroup',
            name='change_type',
            field=models.SmallIntegerField(choices=[(1, b'add user to group'), (2, b'remove user from group')], default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historyownertopermission',
            name='change_type',
            field=models.SmallIntegerField(choices=[(1, b'add permission'), (2, b'remove permission')], default=None),
            preserve_default=False,
        ),
    ]
