# Generated by Django 3.1.5 on 2021-03-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protector', '0008_auto_20191128_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historygenericusertogroup',
            name='change_type',
            field=models.SmallIntegerField(choices=[(1, 'add user to group'), (2, 'remove user from group'), (3, 'role changes')]),
        ),
        migrations.AlterField(
            model_name='historyownertopermission',
            name='change_type',
            field=models.SmallIntegerField(choices=[(1, 'add permission'), (2, 'remove permission'), (3, 'role changes')]),
        ),
        migrations.AlterField(
            model_name='permissioninfo',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='restriction',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='restriction',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='restriction',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
