# Generated by Django 3.1.5 on 2021-03-02 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('protector', '0010_auto_20210302_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericusertogroup',
            name='group_content_type',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='group content type'),
        ),
        migrations.AlterField(
            model_name='historygenericusertogroup',
            name='group_content_type',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='group content type'),
        ),
    ]
