# Generated by Django 4.2.13 on 2024-07-02 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('protector', '0011_auto_20210302_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericusertogroup',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_group_relations', to=settings.AUTH_USER_MODEL, verbose_name='responsible'),
        ),
        migrations.AlterField(
            model_name='genericusertogroup',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_generic_user_relations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historygenericusertogroup',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_group_relations', to=settings.AUTH_USER_MODEL, verbose_name='responsible'),
        ),
        migrations.AlterField(
            model_name='historygenericusertogroup',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_generic_user_relations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historyownertopermission',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_restriction_group_relations', to='contenttypes.contenttype', verbose_name='object type'),
        ),
        migrations.AlterField(
            model_name='historyownertopermission',
            name='owner_content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_restricted_object_relations', to='contenttypes.contenttype', verbose_name='owner type'),
        ),
        migrations.AlterField(
            model_name='historyownertopermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_generic_restriction_relations', to='auth.permission', verbose_name='permission'),
        ),
        migrations.AlterField(
            model_name='historyownertopermission',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_responsible', to=settings.AUTH_USER_MODEL, verbose_name='responsible'),
        ),
        migrations.AlterField(
            model_name='ownertopermission',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_restriction_group_relations', to='contenttypes.contenttype', verbose_name='object type'),
        ),
        migrations.AlterField(
            model_name='ownertopermission',
            name='owner_content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_restricted_object_relations', to='contenttypes.contenttype', verbose_name='owner type'),
        ),
        migrations.AlterField(
            model_name='ownertopermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_generic_restriction_relations', to='auth.permission', verbose_name='permission'),
        ),
        migrations.AlterField(
            model_name='ownertopermission',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_responsible', to=settings.AUTH_USER_MODEL, verbose_name='responsible'),
        ),
    ]
