# Generated by Django 3.2.11 on 2024-10-09 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protector', '0012_alter_genericusertogroup_responsible_and_more'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='historygenericusertogroup',
            index_together=set(),
        ),
        migrations.AlterIndexTogether(
            name='ownertopermission',
            index_together=set(),
        ),
        migrations.AddIndex(
            model_name='historygenericusertogroup',
            index=models.Index(fields=['group_content_type', 'group_id', 'user'], name='protector_h_group_c_78d8db_idx'),
        ),
        migrations.AddIndex(
            model_name='ownertopermission',
            index=models.Index(fields=['owner_content_type', 'owner_object_id'], name='protector_o_owner_c_a45572_idx'),
        ),
        migrations.AddIndex(
            model_name='ownertopermission',
            index=models.Index(fields=['content_type', 'object_id', 'permission'], name='protector_o_content_5d544b_idx'),
        ),
    ]
